### ISSUE TITLE
.git folder has been published to npm

### ISSUE THREAD

**Issue by DanAbb** [danielglennross/hapi-dribble#3]
`npm ERR! code EISGIT`
`hapi-dribble: Appears to be a git repo or submodule.`

Hey man, getting this error when trying to run npm install after the original installation. 

Seems the `.git` folder may have been published to npm by mistake? `npm publish` should automatically ignore the `.git` folder but whenever I install the module its there.

Can you try removing the `.git` folder and republishing the package?

**Comment by danielglennross** [comment]
Repacked with npm@5.0.0
